/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.eltex;

public class App {
    public String getGreeting() {
        return "Hello World!!!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        User user1 = new User("Ivan", 1);
        System.out.println(user1.toString());
    }


}
